---
title: "Demo on fitting the LLM-SSM"
output:
  html_document:
    df_print: paged
---
We will use the time series for internal combustion engine, in the file "internal_combustion_engine.csv". 

You need a few packages installed.

```{r warning=FALSE, message=FALSE}
#load packages
library(dplyr)
library(readr)
library(kableExtra)
library(ggplot2)
library(gridExtra)
library(knitr)
```

```{r}
#Reading the data in
combustion_df <- read_csv("internal_combustion_engine_quarterly.csv")
glimpse(combustion_df)
```

```{r}
#Hyperparameter estimation and Kalman Filtering
YY <- combustion_df %>% pull(combustion)
combustion <- YY
#parameter estimation
source("parameter_estimator3.R")
min_out_combustion <- par_est3(YY)
```

```{r}
#Diffuse Kalman Filter
source("dkfLLMvard.R")
dkf_out_combustion <- dkf.llm.vard(min_out_combustion, YY)
```


Hyperparameters

```{r}
#Estimated hyperparameters
eps <- dkf_out_combustion$sigma.eps
gnu <- dkf_out_combustion$sigma.gnu
eta <- dkf_out_combustion$sigma.eta
delta <- dkf_out_combustion$delta
label <- c("$\\sigma_{\\epsilon}$", "$\\sigma_{\\nu}$", "$\\sigma_{\\eta}$", "$\\delta$")
val_combustion <- c(eps, gnu, eta, delta)
#
tt <-  data.frame(Parameter = label,  val_combustion)
kable(tt, col.names = c("Parameter", ""), booktabs = T, escape = F, align = rep("c",2))
```


```{r}
#The smoothing stage
source("smfilter.R")
sm_out_combustion <- smfilt(dkf_out_combustion)
```

```{r}
#alpha is the predicted state vector
alpha <- sm_out_combustion$alpha
```

```{r}
ll <- dkf_out_combustion$ll
# mu
Z1 <- matrix(c(1,0),1,2)
mu <- alpha[1,]
# beta
Z2 <- matrix(c(0,1),1,2)
beta <- alpha[2,]
first_derivative_combustion <- alpha[2,]
#intercept
time <- seq(1,ll)
int <- mu - beta * time 

df_combustion <- tibble(mu, beta, int, time) %>% 
  mutate(Date = seq(as.Date("2005/1/1"), as.Date("2018/9/30"), by = "quarter")) %>%
  mutate(combustion = YY)
```

Some plots

```{r}
p5_combustion <- ggplot(df_combustion, aes(x = Date, y = combustion)) +
  geom_line() +
  geom_line(aes(x=Date, y = mu), col="coral2", size = 1.3) +
  labs(y = "Observed and signal") +
  ggtitle("internal combustion engine")

p6_combustion <- ggplot(subset(df_combustion,time>3), aes(x=Date, y = beta*10 + 300)) +
  geom_line(col="aquamarine2", size = 1.3) +
  geom_line(aes(x = Date, y = mu), col = "coral2", size = 1.3) +
  scale_y_continuous(name = "Signal", 
    sec.axis = sec_axis(~.*0.1 - 30, name = "First Derivative")) + 
  theme(
      axis.title.y = element_text(color = "coral2", face = "bold"),
      axis.title.y.right = element_text(color = "aquamarine2", face = "bold")) +
  geom_vline(xintercept=as.numeric(df_combustion$Date[c(18, 42)]), linetype = "dotted", colour = "black") +
  geom_hline(yintercept = 300, color = "black") +
  ggtitle("internal combustion engine")

```

```{r}
grid.arrange(p5_combustion, p6_combustion, nrow = 1)
```

FORECASTING

```{r}
source("forecast_alpha.R")
k <- 8 # HOW MANY FORECASTS TO PRODUCE
#
forecast_out_state_combustion <- forecast_alpha(dkf_out_combustion, k)
```

```{r}
yy <- combustion
#
alpha_f <- forecast_out_state_combustion$alpha_hat
signal_forecast <- alpha_f[1,]
derivative_forecast <- alpha_f[2,]
forecast_data <- tibble(signal_forecast, derivative_forecast, Date = seq(as.Date("2018/12/1"), as.Date("2020/9/30"), by = "quarter"))
# 
ggplot(forecast_data, aes(x = Date, y = derivative_forecast * 9 + 344)) +
  geom_line(col = "aquamarine2", size = 1.3)+
  geom_line(aes(x = Date, y = signal_forecast), col = "coral2", size = 1.3) +
  scale_y_continuous(name = "Forecast of Counts", 
    sec.axis = sec_axis(~.*1/9 - 344/9, name = "Forecast of First Derivative")) + 
  theme(
      axis.title.y = element_text(color = "coral2"),
      axis.title.y.right = element_text(color = "aquamarine2")) + 
  geom_hline(yintercept = 344, color = "aquamarine2", linetype = "dotted") +
  ggtitle("internal combustion engine")
```


